/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameinterface;

import gui.geowars;

/**
 *
 * @author Jonas Lauwers <jonas.lauwers AT gmail.org>
 */
public class GamePanel extends Menu {

    private int score;
    private int multiplier;
    private int currency;

    /**
     * Creates new form GamePanel
     */
    public GamePanel(Gui frame, geowars game) {
        super(frame);
        initComponents();
        game.setView(this);
        jPanel1.add(game);
        this.setOpaque(true);
    }

    public void setScore(int score) {
        this.score = score;
        scoreValue.setText(String.valueOf(score));
    }

    public void setMultiplier(int multiplier) {
        this.multiplier = multiplier;
        multiplierValue.setText(String.valueOf(multiplier) + "x");
    }

    public void setCurrency(int currency) {
        this.currency = currency;
        currencyValue.setText(String.valueOf(currency));
    }
    
    public void stop() {
        frame.setFinishedScore(score, currency);
        frame.switchMenu("gameover");
        jPanel1.remove(frame.getGame());
        frame.stop();
        resetGame();
    }
    
    public void resetGame() {
        this.score = 0;
        this.multiplier = 1;
        this.currency = 0;
        geowars game = frame.getGame();
        game.setView(this);
        jPanel1.add(game);
    }
    
    public void pause() {
        frame.pause();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreLabel = new javax.swing.JLabel();
        multiplierLabel = new javax.swing.JLabel();
        scoreValue = new javax.swing.JLabel();
        multiplierValue = new javax.swing.JLabel();
        expLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        currencyValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(73, 144, 255));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        scoreLabel.setFont(scoreLabel.getFont());
        scoreLabel.setText("Score:");

        multiplierLabel.setText("Multiplier:");

        scoreValue.setFont(scoreValue.getFont());
        scoreValue.setText("0");

        multiplierValue.setFont(multiplierValue.getFont());
        multiplierValue.setText("1x");

        expLabel.setText("Currency:");

        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 700));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 700));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        currencyValue.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scoreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiplierLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiplierValue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currencyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(scoreValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(multiplierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(multiplierValue, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(expLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currencyValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currencyValue;
    private javax.swing.JLabel expLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel multiplierLabel;
    private javax.swing.JLabel multiplierValue;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreValue;
    // End of variables declaration//GEN-END:variables
}
