/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameinterface;

import gui.Controller;
import gui.geowars;

/**
 *
 * @author Jonas Lauwers <jonas.lauwers AT gmail.org>
 */
public class GamePanel extends Menu {

    private geowars game;
    private int score;
    private int experience;
    private int multiplier;

    /**
     * Creates new form GamePanel
     */
    public GamePanel(Gui frame) {
        super(frame);
        initComponents();
        this.game = new geowars(this);
        jPanel1.add(this.game);
        this.setOpaque(true);
    }

    public void setScore(int score) {
        this.score = score;
        scoreValue.setText(String.valueOf(score));
    }

    public void setMultiplier(int multiplier) {
        this.multiplier = multiplier;
        multiplierValue.setText(String.valueOf(multiplier) + "x");
    }

    public void setExperience(int experience) {
        this.experience = experience;
        expValue.setText(String.valueOf(experience));
    }

    public void pause() {
        game.setVisible(false);
        frame.switchMenu("pause");
    }
    
    public void resetGame() {
        jPanel1.remove(game);
        this.game = new geowars(this);
        jPanel1.add(game);
    }
    
    public void stop() {
        frame.addScore(score, multiplier);
        jPanel1.remove(game);
        game = new geowars(this);
        jPanel1.add(game);
        frame.switchMenu("gameover");
    }

    public void start() {
        game.setVisible(true);
        game.setFocusable(true);
        game.requestFocus();
        if (game.isPaused()) {
            game.resume();
        } else {
            game.run();
        }
    }

    public void setDifficulty(String type) {
        //nothing  yet to do :)
    }

    public boolean isPaused() {
        return game.isPaused();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreLabel = new javax.swing.JLabel();
        multiplierLabel = new javax.swing.JLabel();
        scoreValue = new javax.swing.JLabel();
        multiplierValue = new javax.swing.JLabel();
        expLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        expValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(73, 144, 255));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        scoreLabel.setFont(scoreLabel.getFont());
        scoreLabel.setText("Score:");

        multiplierLabel.setText("Multiplier:");

        scoreValue.setFont(scoreValue.getFont());
        scoreValue.setText("0");

        multiplierValue.setFont(multiplierValue.getFont());
        multiplierValue.setText("1x");

        expLabel.setText("Exp:");

        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 700));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 700));
        jPanel1.setLayout(new java.awt.GridLayout());

        expValue.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scoreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiplierLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiplierValue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expValue, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(scoreValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(multiplierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(multiplierValue, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(expLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(expValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel expLabel;
    private javax.swing.JLabel expValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel multiplierLabel;
    private javax.swing.JLabel multiplierValue;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreValue;
    // End of variables declaration//GEN-END:variables
}
