/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameinterface;

/**
 *
 * @author nicovandenbrico
 */
public class MainMenu extends Menu {
    
    /**
     * Creates new form mainmenu
     */
    public MainMenu(Gui frame) {
        super(frame);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        highScoreButton = new javax.swing.JButton();
        storeButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        settingsButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(getFont());
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 560));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 560));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 560));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Mainframe/Logo-1.png"))); // NOI18N
        logoLabel.setText("jLabel1");
        logoLabel.setFocusCycleRoot(true);
        logoLabel.setMaximumSize(new java.awt.Dimension(350, 205));
        logoLabel.setMinimumSize(new java.awt.Dimension(350, 205));
        logoLabel.setPreferredSize(new java.awt.Dimension(350, 205));

        playButton.setBackground(new java.awt.Color(26, 35, 50));
        playButton.setFont(getFont());
        playButton.setForeground(new java.awt.Color(26, 35, 50));
        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Buttons/Button-1.png"))); // NOI18N
        playButton.setText("Play");
        playButton.setToolTipText("");
        playButton.setBorderPainted(false);
        playButton.setContentAreaFilled(false);
        playButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playButton.setIconTextGap(0);
        playButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        playButton.setMaximumSize(new java.awt.Dimension(300, 77));
        playButton.setMinimumSize(new java.awt.Dimension(300, 77));
        playButton.setPreferredSize(new java.awt.Dimension(300, 77));
        playButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Buttons/Button-Pressed-1.png"))); // NOI18N
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        highScoreButton.setBackground(new java.awt.Color(26, 35, 50));
        highScoreButton.setFont(getFont());
        highScoreButton.setForeground(new java.awt.Color(26, 35, 50));
        highScoreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Buttons/Button-1.png"))); // NOI18N
        highScoreButton.setText("HighScore");
        highScoreButton.setToolTipText("");
        highScoreButton.setBorderPainted(false);
        highScoreButton.setContentAreaFilled(false);
        highScoreButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        highScoreButton.setIconTextGap(0);
        highScoreButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        highScoreButton.setMaximumSize(new java.awt.Dimension(300, 77));
        highScoreButton.setMinimumSize(new java.awt.Dimension(300, 77));
        highScoreButton.setPreferredSize(new java.awt.Dimension(300, 77));
        highScoreButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Buttons/Button-Pressed-1.png"))); // NOI18N
        highScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoreButtonActionPerformed(evt);
            }
        });

        storeButton.setBackground(new java.awt.Color(26, 35, 50));
        storeButton.setFont(getFont());
        storeButton.setForeground(new java.awt.Color(26, 35, 50));
        storeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Buttons/Button-1.png"))); // NOI18N
        storeButton.setText("Store");
        storeButton.setToolTipText("");
        storeButton.setBorderPainted(false);
        storeButton.setContentAreaFilled(false);
        storeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        storeButton.setIconTextGap(0);
        storeButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        storeButton.setMaximumSize(new java.awt.Dimension(300, 77));
        storeButton.setMinimumSize(new java.awt.Dimension(300, 77));
        storeButton.setPreferredSize(new java.awt.Dimension(300, 77));
        storeButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Buttons/Button-Pressed-1.png"))); // NOI18N
        storeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highScoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(storeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(highScoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(storeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logoLabel.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(jPanel1.getBackground());
        jPanel2.setMaximumSize(new java.awt.Dimension(120, 70));
        jPanel2.setMinimumSize(new java.awt.Dimension(120, 70));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 70));

        settingsButton.setBackground(new java.awt.Color(26, 35, 50));
        settingsButton.setFont(getFont());
        settingsButton.setForeground(new java.awt.Color(26, 35, 50));
        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Buttons/Button-Settings-1.png"))); // NOI18N
        settingsButton.setBorderPainted(false);
        settingsButton.setContentAreaFilled(false);
        settingsButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        settingsButton.setMaximumSize(new java.awt.Dimension(45, 45));
        settingsButton.setMinimumSize(new java.awt.Dimension(45, 45));
        settingsButton.setPreferredSize(new java.awt.Dimension(45, 45));
        settingsButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Buttons/Button-Settings-Pressed-1.png"))); // NOI18N
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        infoButton.setBackground(new java.awt.Color(26, 35, 50));
        infoButton.setFont(getFont());
        infoButton.setForeground(new java.awt.Color(26, 35, 50));
        infoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Buttons/Button-Help-1.png"))); // NOI18N
        infoButton.setBorderPainted(false);
        infoButton.setContentAreaFilled(false);
        infoButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        infoButton.setMaximumSize(new java.awt.Dimension(45, 45));
        infoButton.setMinimumSize(new java.awt.Dimension(45, 45));
        infoButton.setPreferredSize(new java.awt.Dimension(45, 45));
        infoButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Buttons/Button-Help-Pressed-1.png"))); // NOI18N
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void storeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeButtonActionPerformed
        frame.switchMenu("store");
    }//GEN-LAST:event_storeButtonActionPerformed

    private void highScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoreButtonActionPerformed
        frame.switchMenu("highScore");
    }//GEN-LAST:event_highScoreButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        frame.switchMenu("difficulty");
    }//GEN-LAST:event_playButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        frame.switchMenu("info");
    }//GEN-LAST:event_infoButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        frame.switchMenu("settings");
    }//GEN-LAST:event_settingsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton highScoreButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton playButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JButton storeButton;
    // End of variables declaration//GEN-END:variables
}
